name: Azure Deployment

on:
  push:
    branches:
      - dev  # Trigger workflow on push to the main branch

jobs:
  Myprovisiontenantpowershellexecution:
    name: OS
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run PowerShell Script
      shell: pwsh
      run: |
        ./scripts/generate_tfvars.ps1

    - name: Upload terraform.tfvars.json
      uses: actions/upload-artifact@v3
      with:
        name: terraform-tfvars
        path: terraform.tfvars.json

  