Workflow Script
name: Azure Deployment

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  query-resources:
    name: Query Azure Resources
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run PowerShell Script
      shell: pwsh
      run: |
        ./scripts/generate_tfvars.ps1

    - name: Upload terraform.tfvars.json
      uses: actions/upload-artifact@v3
      with:
        name: terraform-tfvars
        path: terraform.tfvars.json

  terraform-deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    needs: query-resources

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download terraform.tfvars.json
      uses: actions/download-artifact@v3
      with:
        name: terraform-tfvars

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6  # Use your desired version

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Plan Terraform Deployment
      run: terraform plan -var-file=../terraform.tfvars.json
      working-directory: ./terraform

    - name: Apply Terraform Deployment
      run: terraform apply -auto-approve -var-file=../terraform.tfvars.json
      working-directory: ./terraform
